services:
  - type: worker
    name: usdt-mining-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: DATABASE_URL
        value: sqlite:///mining_bot.db
      - key: PYTHON_VERSION
        value: 3.11.6
